<?php
/**
 * Tool Landing Page Template
 * Auto-generated by GMKB_Tool_Pages
 *
 * This template displays individual AI tool pages at /tools/{tool-slug}/
 */

if (!defined('ABSPATH')) {
    exit;
}

get_header();

// Initialize the tool pages class and render
if (class_exists('GMKB_Tool_Pages')) {
    $pages = GMKB_Tool_Pages::instance();
    $pages->render_tool_page();
} else {
    // Fallback if class not loaded - indicates plugin configuration issue
    ?>
    <style>
        .gmkb-tool-page {
            max-width: 1200px;
            margin: 0 auto;
            padding: 2rem 1rem;
        }
        .gmkb-tool-page .gmkb-error {
            text-align: center;
            padding: 40px;
        }
        .gmkb-tool-page .gmkb-error a {
            display: inline-block;
            margin-top: 1rem;
            color: #3b82f6;
            text-decoration: none;
        }
        .gmkb-tool-page .gmkb-error a:hover {
            text-decoration: underline;
        }
    </style>
    <div class="gmkb-tool-page">
        <div class="gmkb-error">
            <h2>Tool Unavailable</h2>
            <p>This tool is currently unavailable due to a configuration issue. Please contact support if this problem persists.</p>
            <a href="<?php echo esc_url(home_url('/tools/')); ?>">← Back to Tools</a>
        </div>
    </div>
    <?php
}

get_footer();
