<?php
/**
 * Tool Landing Page Template
 * Auto-generated by GMKB_Tool_Pages
 *
 * This template displays individual AI tool pages at /tools/{tool-slug}/
 */

if (!defined('ABSPATH')) {
    exit;
}

get_header();

// Initialize the tool pages class and render
if (class_exists('GMKB_Tool_Pages')) {
    $pages = GMKB_Tool_Pages::instance();
    $pages->render_tool_page();
} else {
    // Fallback if class not loaded
    ?>
    <div class="gmkb-tool-page" style="max-width: 1200px; margin: 0 auto; padding: 2rem 1rem;">
        <div class="gmkb-error" style="text-align: center; padding: 40px;">
            <h2>Tool Not Available</h2>
            <p>This tool is currently loading. If this message persists, please refresh the page.</p>
            <a href="<?php echo esc_url(home_url('/tools/')); ?>">← Back to Tools</a>
        </div>
    </div>
    <?php
}

get_footer();
