<?php
/**
 * Tools Directory Template
 * Auto-generated by GMKB_Tool_Pages
 *
 * This template displays the AI tools directory at /tools/
 */

if (!defined('ABSPATH')) {
    exit;
}

get_header();

// Initialize the tool pages class and render
if (class_exists('GMKB_Tool_Pages')) {
    $pages = GMKB_Tool_Pages::instance();
    $pages->render_directory_page();
} else {
    // Fallback if class not loaded
    ?>
    <div class="gmkb-tools-directory-page" style="max-width: 1200px; margin: 0 auto; padding: 2rem 1rem;">
        <div class="gmkb-error" style="text-align: center; padding: 40px;">
            <h2>Tools Directory</h2>
            <p>The tools directory is loading. If this message persists, please refresh the page.</p>
        </div>
    </div>
    <?php
}

get_footer();
